# Generated by Django 5.1.7 on 2025-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
